const products = [
    {
        id: 1,
        name: "Gaming Laptop",
        category: "Laptops",
        price: 1200,
        description: "High-performance laptop for gaming and productivity.",
        image: "https://via.placeholder.com/150?text=Gaming+Laptop",
    },
    {
        id: 2,
        name: "Smartphone Pro",
        category: "Smartphones",
        price: 999,
        description: "Flagship smartphone with cutting-edge features.",
        image: "https://via.placeholder.com/150?text=Smartphone+Pro",
    },
    {
        id: 3,
        name: "Wireless Headphones",
        category: "Audio",
        price: 199,
        description: "Noise-cancelling wireless headphones for immersive sound.",
        image: "https://via.placeholder.com/150?text=Wireless+Headphones",
    },
    {
        id: 4,
        name: "Mechanical Keyboard",
        category: "Accessories",
        price: 89,
        description: "Durable mechanical keyboard with customizable RGB lighting.",
        image: "https://via.placeholder.com/150?text=Mechanical+Keyboard",
    },
    {
        id: 5,
        name: "Gaming Console",
        category: "Gaming",
        price: 499,
        description: "Next-gen gaming console for an unparalleled experience.",
        image: "https://via.placeholder.com/150?text=Gaming+Console",
    },
    {
        id: 6,
        name: "4K Monitor",
        category: "Laptops",
        price: 350,
        description: "Ultra HD monitor for stunning visuals and productivity.",
        image: "https://via.placeholder.com/150?text=4K+Monitor",
    },
    {
        id: 7,
        name: "Smartwatch",
        category: "Smartphones",
        price: 299,
        description: "Stylish smartwatch with health tracking and notifications.",
        image: "https://via.placeholder.com/150?text=Smartwatch",
    },
    {
        id: 8,
        name: "Bluetooth Speaker",
        category: "Audio",
        price: 149,
        description: "Portable Bluetooth speaker with powerful sound.",
        image: "https://via.placeholder.com/150?text=Bluetooth+Speaker",
    },
    {
        id: 9,
        name: "Gaming Mouse",
        category: "Accessories",
        price: 59,
        description: "Ergonomic gaming mouse with high precision and RGB lighting.",
        image: "https://via.placeholder.com/150?text=Gaming+Mouse",
    },
    {
        id: 10,
        name: "VR Headset",
        category: "Gaming",
        price: 399,
        description: "Virtual reality headset for immersive gaming experiences.",
        image: "https://via.placeholder.com/150?text=VR+Headset",
    },
    {
        id: 11,
        name: "Tablet Pro",
        category: "Smartphones",
        price: 799,
        description: "High-performance tablet for work and entertainment.",
        image: "https://via.placeholder.com/150?text=Tablet+Pro",
    },
];

let filterproducts=products.filter((product) => product.category === "Smartphones");    
console.log(filterproducts);